---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: brokers.kubevent.io
spec:
  additionalPrinterColumns: []
  group: kubevent.io
  names:
    kind: Broker
    plural: brokers
    shortNames: []
    singular: broker
  scope: Cluster
  subresources: {}
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rules.kubevent.io
spec:
  additionalPrinterColumns: []
  group: kubevent.io
  names:
    kind: Rule
    plural: rules
    shortNames: []
    singular: rule
  scope: Cluster
  subresources: {}
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rulebindings.kubevent.io
spec:
  additionalPrinterColumns: []
  group: kubevent.io
  names:
    kind: RuleBinding
    plural: rulebindings
    shortNames: []
    singular: rulebinding
  scope: Cluster
  subresources: {}
  versions:
    - name: v1alpha1
      served: true
      storage: true
