---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: brokers.kubevent.io
spec:
  group: kubevent.io
  names:
    kind: Broker
    plural: brokers
    shortNames: []
    singular: broker
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rules.kubevent.io
spec:
  group: kubevent.io
  names:
    kind: Rule
    plural: rules
    shortNames: []
    singular: rule
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rulebrokersbindings.kubevent.io
spec:
  group: kubevent.io
  names:
    kind: RuleBrokersBinding
    plural: rulebrokersbindings
    shortNames: []
    singular: rulebrokersbinding
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
